import type { Metadata } from "next";

import localFont from "next/font/local";

import "../style/index.scss";
import App from "./app";

const suisselntl = localFont({
  src: [
    {
      path: "../../public/assets/fonts/suisseIntl-light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/suisseIntl.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Home Page | Misr Italia Properties - life Inspired By You",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={suisselntl.className}>
        <App>{children}</App>
      </body>
    </html>
  );
}
